// This file is auto-generated. Do not edit this file manually.
// To regenerate the schema, run:
// `npx @better-auth/cli generate --output generatedSchema.ts -y`

import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export const tables = {
	accounts: defineTable({
		accessToken: v.optional(v.union(v.null(), v.string())),
		accessTokenExpiresAt: v.optional(v.union(v.null(), v.number())),
		accountId: v.string(),
		createdAt: v.number(),
		idToken: v.optional(v.union(v.null(), v.string())),
		password: v.optional(v.union(v.null(), v.string())),
		providerId: v.string(),
		refreshToken: v.optional(v.union(v.null(), v.string())),
		refreshTokenExpiresAt: v.optional(v.union(v.null(), v.number())),
		scope: v.optional(v.union(v.null(), v.string())),
		updatedAt: v.number(),
		userId: v.string(),
	}),
	jwks: defineTable({
		createdAt: v.number(),
		privateKey: v.string(),
		publicKey: v.string(),
	}),
	sessions: defineTable({
		createdAt: v.number(),
		expiresAt: v.number(),
		ipAddress: v.optional(v.union(v.null(), v.string())),
		token: v.string(),
		updatedAt: v.number(),
		userAgent: v.optional(v.union(v.null(), v.string())),
		userId: v.string(),
	}),
	users: defineTable({
		createdAt: v.number(),
		email: v.string(),
		emailVerified: v.boolean(),
		image: v.optional(v.union(v.null(), v.string())),
		isAnonymous: v.optional(v.union(v.null(), v.boolean())),
		name: v.string(),
		tier: v.optional(v.union(v.null(), v.string())),
		updatedAt: v.number(),
		userId: v.optional(v.union(v.null(), v.string())),
	}),
	verifications: defineTable({
		createdAt: v.number(),
		expiresAt: v.number(),
		identifier: v.string(),
		updatedAt: v.number(),
		value: v.string(),
	}),
};

const schema = defineSchema(tables);

export default schema;
